#!/usr/bin/env python3
"""Generate one printable page holding several documents at once.

The manager ticks the documents they want in the popup, answers each
question once - the apartment, and any question only a ticked document
asks - and every ticked document is filled in from those answers and
printed together, each starting on a new sheet of paper.

Nothing here is written twice: each document's body comes from its own
generator's `render_body`, from the same live master, so the combined page
and the single-document pages cannot say different things. The Plaster
Walls Addendum is left out - it is no longer in use, and names one fixed
address rather than the apartment picked.

Usage:
    python documents/print/generate_print_packet.py
"""
from __future__ import annotations

import html
import importlib.util
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
OUTPUT = HERE / "documents_print.html"

TITLE = "Documents"


def _load(name: str):
    spec = importlib.util.spec_from_file_location(name, HERE / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault(spec.name, module)
    spec.loader.exec_module(module)
    return sys.modules[spec.name]


lease = _load("generate_print_lease")
deposit = _load("generate_print_deposit")
application = _load("generate_print_application")

# (key, name in the popup, generator, live master, ticked by default), in
# the order they print - the order they are used.
DOCUMENTS = (
    ("application", "Application", application, REPO_ROOT / "documents" / "application.md", False),
    ("lease", "Lease", lease, REPO_ROOT / "documents" / "lease.md", True),
    ("deposit", "Security deposit", deposit, REPO_ROOT / "documents" / "security_deposit.md", True),
)

FOOTER_NOTE = """
<div class="footer-note">
  These documents are generated by <code>documents/print/generate_print_packet.py</code>
  from the same masters as each one's own page (<code>documents/application.md</code>,
  <code>documents/lease.md</code>, <code>documents/security_deposit.md</code>). This note
  will not appear on a printed copy. Regenerate after editing any of them or
  <code>documents/properties.json</code>. Printed together, "Page X of Y" counts the
  whole printout, not each document.
</div>"""


def section(key: str, module, source: Path) -> str:
    body = module.render_body(source.read_text(encoding="utf-8"))
    # Each document has a premises blank with id="premises"; on one page
    # an id may appear once, so here they are marked data-premises, which
    # the picker fills just the same.
    if body.count('id="premises"') != 1:
        raise SystemExit(f"{source.name}: expected exactly one premises blank.")
    body = body.replace('id="premises"', "data-premises")
    return (f'<section class="document sheet" data-doc="{key}">\n'
            + lease.render_title_block(lease.COMPANY_NAME, module.SUBTITLE)
            + body + "\n</section>")


def check_unique_ids(page: str) -> None:
    ids = re.findall(r'\sid="([^"]+)"', page)
    repeated = sorted({i for i in ids if ids.count(i) > 1})
    if repeated:
        raise SystemExit(f"Two documents share the id(s) {repeated} - the combined page needs each once.")


def generate() -> str:
    css = "".join(module.EXTRA_CSS for _, _, module, _, _ in DOCUMENTS)
    head = lease.render_page_head(lease.COMPANY_NAME, TITLE).replace("</style>", css + "</style>", 1)
    body = "\n".join(section(key, module, source) for key, _, module, source, _ in DOCUMENTS)
    # Every question once: the apartment is shared by all three, and each
    # document's own boxes are asked only while it is ticked.
    fields = tuple(field + ("application",) for field in application.PICKER_FIELDS)
    choices = tuple((key, name, ticked) for key, name, _, _, ticked in DOCUMENTS)
    head += '<main class="sheet-stack">\n'
    page = head + body + "\n" + FOOTER_NOTE + lease.render_picker_footer("documents", fields, choices,
                                                                          money=application.MONEY_FIELDS)
    check_unique_ids(page)
    return page


def main() -> None:
    OUTPUT.write_text(generate(), encoding="utf-8")
    print(f"Wrote {OUTPUT}.")


if __name__ == "__main__":
    main()
